# Generated by Django 5.0.1 on 2024-01-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facultyDataManager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="contactNumer",
            field=models.CharField(default="1234567890", max_length=10),
            preserve_default=False,
        ),
    ]
