# Generated by Django 5.0.1 on 2024-01-23 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facultyDataManager", "0002_faculty_contactnumer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookpublication",
            name="faculty_id",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="faculty_id",
        ),
        migrations.RemoveField(
            model_name="conferencepublication",
            name="faculty_id",
        ),
        migrations.RemoveField(
            model_name="journalpublication",
            name="faculty_id",
        ),
        migrations.RemoveField(
            model_name="patent",
            name="faculty_faculty_id",
        ),
    ]
