# Generated by Django 5.0.1 on 2024-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facultyDataManager", "0003_remove_bookpublication_faculty_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="book_publications",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="conference_publications",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="journal_publications",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="patents",
        ),
        migrations.AddField(
            model_name="bookpublication",
            name="faculty_id",
            field=models.CharField(default="T-CSE-01", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certification",
            name="faculty_id",
            field=models.CharField(default="T-CSE-01", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conferencepublication",
            name="faculty_id",
            field=models.CharField(default="T-CSE-01", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journalpublication",
            name="faculty_id",
            field=models.CharField(default="T-CSE-01", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patent",
            name="faculty_id",
            field=models.CharField(default="T-CSE-01", max_length=20),
            preserve_default=False,
        ),
    ]
