# Generated by Django 5.0.1 on 2024-01-23 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facultyDataManager", "0004_remove_faculty_book_publications_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faculty",
            old_name="contactNumer",
            new_name="contactNumber",
        ),
    ]
