# Generated by Django 5.0.1 on 2024-01-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "facultyDataManager",
            "0006_conferencechair_coursereport_fdp_guestlecture_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="guestlecture",
            old_name="name_of_the_faculty",
            new_name="name_of_the_guest_lecture",
        ),
        migrations.RemoveField(
            model_name="faculty",
            name="password",
        ),
        migrations.AlterField(
            model_name="faculty",
            name="college_level",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="department_level",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
