# Generated by Django 5.0.1 on 2024-01-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyDataManager', '0008_remove_conferencechair_name_of_the_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublication',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencechair',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencepublication',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursereport',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fdp',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestlecture',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalpublication',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='academic_year',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
